volumes:
  db-store:
services:
  app:
    container_name: basis-php-apache
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - ./backend:/var/www/html/
    ports:
    - 6060:80
    depends_on:
    - db
  db:
    container_name: basis-mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - db-store:/var/www/mysql
    ports:
    - 9000:3306
    #デフォルトログインユーザーの指定
    user: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  adminer:
    image: adminer:latest
    container_name: basis-adminer
    ports:
    - 10000:8080
    depends_on:
    - db